name: Install and Test Environment
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
 
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: eoupv2
          environment-file: environment.yml
          auto-activate-base: false
 
      - name: Check installation
        shell: bash -el {0}
        run: |
          conda activate eoupv2
          jupyter nbconvert --to notebook --execute test_installation.ipynb
 